modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CyclopsMC/EnergeticSheep/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/energeticsheep"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="energeticsheep"
version="${file.jarVersion}"
displayName="EnergeticSheep"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/energeticsheep.json"
description='''
Sheep that generate energy
'''
[[dependencies.energeticsheep]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energeticsheep]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energeticsheep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,]"
    ordering="NONE"
    side="BOTH"
