modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/EnergeticSheep/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/energeticsheep"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="energeticsheep"
version="${file.jarVersion}"
displayName="EnergeticSheep"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/energeticsheep.json"
description='''
Sheep that generate energy
'''
[[dependencies.energeticsheep]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energeticsheep]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energeticsheep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
